package com.reasontouch.feature.chords

import com.reasontouch.core.data.ChordEvent

/**
 * Represents a candidate progression generated by the composition engine.
 *
 * Multiple GeneratedProgressions may be returned for a single request,
 * allowing the user to choose between different musical ideas.
 */
data class GeneratedProgression(

    /**
     * The generated chord sequence.
     */
    val chords: List<ChordEvent>,

    /**
     * Relative confidence (0.0–1.0).
     *
     * This is NOT a measure of correctness.
     * It simply reflects how closely the generated progression
     * matches the requested musical intent.
     */
    val confidence: Float,

    /**
     * Short explanation describing why this progression
     * was suggested.
     */
    val explanation: String
)