package com.reasontouch.feature.chords

import com.reasontouch.feature.chords.TheoryChord

/**
 * Represents a candidate progression generated by the composition engine.
 *
 * A GeneratedProgression is purely a harmonic suggestion.
 * It contains only musical information (TheoryChord objects).
 *
 * It does NOT contain:
 * - Session IDs
 * - Bar indices
 * - MIDI data
 * - Database references
 *
 * Only after the user accepts a suggestion does the generator
 * convert TheoryChords into ChordEvents and add them to the session.
 *
 * Multiple GeneratedProgressions may be returned for a single request,
 * allowing the user to choose between different musical ideas.
 */
data class GeneratedProgression(
    /**
     * The generated chord sequence as music theory objects.
     *
     * Each TheoryChord contains:
     * - root (e.g., C, Em, F7)
     * - quality (Major, Minor, Dominant7, etc.)
     *
     * No session/persistence data.
     */
    val chords: List<TheoryChord>,

    /**
     * Relative confidence (0.0–1.0).
     *
     * This is NOT a measure of correctness.
     * It simply reflects how closely the generated progression
     * matches the requested musical intent.
     */
    val confidence: Float,

    /**
     * Short explanation describing why this progression
     * was suggested.
     */
    val explanation: String
)